### ISSUE TITLE
Interface Client does not provide update methods

### ISSUE THREAD

**Issue by philippemerle** [Misenko/jOCCI-api#2]
The [Client](https://github.com/Misenko/jOCCI-api/blob/master/src/main/java/cz/cesnet/cloud/occi/api/Client.java) interface does not provide update methods.
So there is no way with jOCCI to update OCCI entities hosted by a remote OCCI server.
At least the Client interface should provide the following method:
  public abstract void update(Entity entity) throws CommunicationException;

This method is required to complete the [jOCCI connector](https://github.com/occiware/ecore/tree/master/clouddesigner/org.occiware.clouddesigner.occi.connector.jocci) of the OCCIware Studio.

**Comment by amarthadan** [comment]
Resolved in EGI-FCTF/jOCCI-api#15
