### ISSUE TITLE
Wiki update - clarification for default value when using 'Compute.MEMORY_ATTRIBUTE_NAME'

### ISSUE THREAD

**Issue by dejanstamenov** [Misenko/jOCCI-api#4]
On the [following](https://github.com/Misenko/jOCCI-api/wiki/Usage-&-examples) Wiki page, at the bottom of the page where the `create` method is explained, it is not clearly stated that the default value of the following code:
`resource.addAttribute(Compute.MEMORY_ATTRIBUTE_NAME, "2048");`
is measured in GBs, and not MBs.

Personally, I think you should point it out on the Wiki page, that in the given example, the virtual machine will be created with 2TB RAM. Recently, I had a scenario of creating lots of virtual machines on the cloud, using the same line of code (_pointed above_) while allocating "1024". The outcome was the server getting stuck, because each virtual machine tried to allocate 1TB RAM.

**Comment by amarthadan** [comment]
The wiki page you're referring to is outdated. In the future, please, use project's main [wiki page](https://github.com/EGI-FCTF/jOCCI-api/wiki). I'll remove the old one to prevent further confusion.

Nevertheless, the mistake was present on the main wiki page as well and I fixed it. Thank you for noticing and sorry for the trouble.
